name: My First Workflow
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
          
      - name: Write Summary from Action
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
            .addHeading('Test Results')
            .addTable([
              [{data: 'File', header: true}, {data: 'Result', header: true}],
              ['foo.js', 'Pass ✅'],
              ['bar.js', 'Fail ❌'],
              ['test.js', 'Pass ✅']
            ])
            .addLink('View staging deployment!', 'https://github.com')
            .write()
      
